email: kbd3ax@virginia.edu
description: >- # this means to ignore newlines until "baseurl:"
  Custom setup for Jekyll-based sites. Provides modified directory
  structures, Gulp-based asset processing, and a custom theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://setup.katherinedonnally.design" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kbdonnally
github_username:  kbdonnally
permalink: /:year/:month/:day/:title/

# Build settings
incremental: true
markdown: kramdown

exclude:
  - _assets
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - tree.txt
  - docs
  - node_modules
  - vendor

collections_dir: collections
# example setup
# collections:
#  people:
#    output: true
#    permalink: /:collection/:slug/

plugins:
   - jekyll-feed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "pages"
    values:
      order: 10

# defaults explained:
# 1. static images are in assets/img/*
# 2. by default, any pages/* document has
#    'order' var of value '10'